#ifndef HTTPMETHOD_HPP_
#define HTTPMETHOD_HPP_

#define HTTP_METHOD_GET "GET"
#define HTTP_METHOD_HEAD "HEAD"
#define HTTP_METHOD_POST "POST"
#define HTTP_METHOD_PUT "PUT"
#define HTTP_METHOD_DELETE "DELETE"
#define HTTP_METHOD_CONNECT "CONNECT"
#define HTTP_METHOD_OPTIONS "OPTIONS"
#define HTTP_METHOD_TRACE "TRACE"
#define HTTP_METHOD_PATCH "PATCH"


#endif